### ISSUE TITLE
Errors because it can't find a log channel before it has a chance to make a template config

### ISSUE THREAD

**Issue by xproot** [CamK06/WinBot#15]
OS: Ubuntu 20.04.3
Dotnet version: 5.0.402
(seems to happen on MacOS Big Sur too)
```
[10-31-2021 9:56 PM] Resources not found!
[10-31-2021 9:56 PM] Downloading resources...
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at WinBot.Util.DiscordSink.<.ctor>b__2_0(Object s, ElapsedEventArgs e) in /home/xproot/Documents/WinBot/Source/Util/DiscordSink.cs:line 26
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
```

If I extract the included Res.zip in the WorkingDirectory instead of letting it download it and do it by itself it works normally

**Comment by CamK06** [comment]
Try the latest commit

**Comment by xproot** [comment]
fixed
