### ISSUE TITLE
Crashes when no log

### ISSUE THREAD

**Issue by xproot** [CamK06/WinBot#31]
`Exception thrown: 'System.IO.DirectoryNotFoundException' in System.Private.CoreLib.dll`

Line 48: `File.AppendAllText($"Logs/{DateTime.Now.ToShortDateString().Replace("/", "-")}.log", finalMessage + "\n");`

```cs
Exception has occurred: CLR/System.IO.DirectoryNotFoundException
An exception of type 'System.IO.DirectoryNotFoundException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'Could not find a part of the path '/home/xproot/WinBot/WorkingDirectory/Logs/2-2-2022.log'.'
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at System.IO.File.AppendAllText(String path, String contents)
   at WinBot.Util.DiscordSink.Emit(LogEvent logEvent) in [/home/xproot/WinBot/Source/Util/DiscordSink.cs]():line 48
   at Serilog.Core.Sinks.SafeAggregateSink.Emit(LogEvent logEvent)
```

idk im just guessing

**Comment by codedipper** [comment]
"System.IO.DirectoryNotFoundException"
Did you delete the logs folder?

**Comment by xproot** [comment]
h closing because h
